mentorFinder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('accounts/', include('accounts.urls')),
    path('employee/', include('employee.urls')),
    path('mentors/', include('mentors.urls')),
    path('appointment/',include('appointment.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mentors/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.mentors_list, name='mentors_list'),
    path('<int:mentor_id>/', views.mentors_details, name='mentors_details'),
    path('search/', views.search, name="search"),
    path('mentorDashboard/', views.mentorDashboard, name='mentorDashboard'),
    path('mentorHistory/', views.mentorHistory, name='mentorHistory'),
    path('done/<appointment_id>', views.done_job, name='done'),
    path('appointmentDate/<appointment_id>', views.appointmentDate, name='appointmentDate'),
]

pages/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='index')
]

mentors/models.py
from django.db import models
from django.contrib.auth import get_user_model
from employee.models import Employee
from datetime import datetime
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from .choices_tpl import divisions_list, district_list, category, sex


User = get_user_model()

class Mentor(models.Model):
        added_by = models.CharField(max_length=200,blank=True, null=True)
        mentor_Name = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
        title = models.CharField(max_length=200)
        professional_degree = models.CharField(max_length=200)
        designation = models.CharField(max_length=200, blank=True)
        specialist_in = models.CharField(max_length=200, blank=True)
        visiting_houre = models.CharField(max_length=200, blank=True)
        visiting_fees = models.CharField(max_length=200)
        descriptions = models.TextField(blank=True)
        sex = models.CharField(max_length=50, default=None, blank=True, choices=sex)
        nid_no = models.CharField(max_length=200,blank=True)
        catagory = models.CharField(max_length=300, default=None, blank=True, choices=category)
        chamber_address = models.CharField(max_length=300,blank=True)
        district = models.CharField(max_length=300, default=None, blank=True, choices=district_list)
        divisions = models.CharField(max_length=300, default=None, blank=True, choices=divisions_list)
        name = models.CharField(max_length=200, null=True, blank=True)
        mentors_picture = models.ImageField(upload_to='photos/dp/mentors/%Y/%m/%d/',blank=True)
        cover_photo_1 = models.ImageField(upload_to='photos/mentors/cover/%Y/%m/%d/',blank=True)
        cover_photo_2 = models.ImageField(upload_to='photos/mentors/cover/%Y/%m/%d/',blank=True)
        cover_photo_3 = models.ImageField(upload_to='photos/mentors/cover/%Y/%m/%d/',blank=True)
        join_date = models.DateTimeField(default=datetime.now, blank=True)
        is_published = models.BooleanField(default=True)
        score = models.IntegerField(default=0, validators=[ MaxValueValidator(5), MinValueValidator(0),])


        def __str__(self):
            return f"{self.mentor_Name}"

        def summary(self):
            return self.descriptions[:150]

        def pub_date_pretty(self):
            return self.pub_date.strftime('%d %B %Y')

mentors/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from .models import Mentor
from accounts.decorators import allowed_users
from mentors.choices import district_list,divisions_list, price_choices, category_list
from appointment.models import Appointment
from appointment.forms import AppointmentUpdateForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.contrib import messages


User = get_user_model()

def mentors_list(request):
    mentors = Mentor.objects.order_by('-join_date')
    
    paginator = Paginator(mentors,6)
    page = request.GET.get('page')
    paged_listings = paginator.get_page(page)

    context = {
        'mentors' : paged_listings
    }
    return render(request,'mentors/mentors_list.html',context)

def mentors_details(request,mentor_id):
    mentors_details = get_object_or_404(Mentor,pk = mentor_id)

    context = {
        'mentors_details' : mentors_details
    }

    return render(request,'mentors/mentors_details.html',context)

def search(request):
    queryset_list = Mentor.objects.order_by('-join_date')

    #Search by keywords
    if 'keywords' in request.GET:
        keywords = request.GET['keywords']
        if keywords:
            queryset_list = queryset_list.filter(title__icontains=keywords)

    #Search by keywords
    if 'name' in request.GET:
        name = request.GET['name']
        if name:
            queryset_list = queryset_list.filter(name__icontains=name)
    
    #Search by category
    if 'category' in request.GET:
        category = request.GET['category']
        if category:
            queryset_list = queryset_list.filter(catagory__iexact=category)

    #Search by Division
    if 'division' in request.GET:
        division = request.GET['division']
        if division:
            queryset_list = queryset_list.filter(divisions__iexact=division)

    #Search by district
    if 'district' in request.GET:
        district = request.GET['district']
        if district:
            queryset_list = queryset_list.filter(district__iexact=district)
    
    context = {
        'district_list' : district_list,
        'divisions_list' : divisions_list,
        'price_choices' : price_choices,
        'mentors' : queryset_list,
        'category' : category_list,
    }
    return render(request,'mentors/search.html',context)

@login_required
@allowed_users(['Mentor'])
def mentorDashboard(request):
    mentor = request.user.username
    user_appointment = Appointment.objects.order_by('-apply_date').filter(mentor_username=mentor, done_job=False)

    context = {
        'appointment': user_appointment,
    }
    return render(request,'mentors/mentorDashboard.html',context)

@login_required
@allowed_users(['Mentor'])
def mentorHistory(request):
    mentor = request.user.username
    user_appointment = Appointment.objects.order_by('-apply_date').filter(mentor_username=mentor, done_job=True)
    context = {
        'appointment': user_appointment,
    }
    return render(request,'mentors/mentor_history.html',context)

@login_required
@allowed_users(['Mentor'])
def done_job(request, appointment_id):
    appointment = Appointment.objects.get(pk=appointment_id)
    appointment.done_job = True
    appointment.save()
    return redirect('mentorDashboard')

@login_required
@allowed_users(['Mentor'])
def appointmentDate(request, appointment_id):
    if request.method == "POST":
        appointment = Appointment.objects.get(pk=appointment_id)
        appointment.appointment_date = request.POST.get('appointment_date')
        appointment.save()
        return redirect('mentorDashboard')

templates/mentors/mentorDashboard.html
{% extends 'base.html' %}
{% load static %}
{% block contant %}
<!-- Mentor home navbar -->
<div class="container">
    {% include 'partials/_alerts.html' %}
<div class="row">
    <div class="col-sm-3">
        {% include 'partials/_userHNav.html' %}
    </div>
    <div class="col-sm-9">
        {% if appointment %}
          <table class="table table-striped table-sm mt-2 search_bar_color">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Name</th>
                  <th scope="col">Phone</th>
                  <th scope="col">Apply Date</th>
                  <th scope="col">Appointment Date</th>
                  <th scope="col">Profile</th>
                  <th scope="col">Is Done</th>
                </tr>
              </thead>
              <tbody>
                {% for appointment in appointment %}
                  <tr>
                      <th scope="row">{{ forloop.counter }}</th>
                      <td>{{ appointment.name }}</td>
                      <td>{{ appointment.phone }}</td>
                      <td>{{ appointment.apply_date_pretty }}</td>
                      {% if appointment.appointment_date %}
                        <td>{{ appointment.appointment_date_pretty }}</td>
                      {% else %}
                        <td>
                          <form action="{% url 'appointmentDate' appointment.id %}" method="POST" class="form-inline">
                            {% csrf_token %}
                            <div class="form-group">
                              <input type="datetime-local" name="appointment_date" class="form-control form-control-sm">
                            </div>
                            <input type="submit" class="btn btn-success btn-sm" value="&#10003">
                          </form>
                      </td>
                      {% endif %}
                      <!-- View Profile -->
                      <td><a href="{% url 'view_profile' appointment.user_id %}" class="btn btn-secondary" >View</a></td>
                      <td class="align-middle">
                        {% if appointment.done_job %}
                          <td class="text-success"><i class="fas fa-check-circle"></i></td>
                        {% else %}
                          <td class="align-middle">
                            <a class="text-danger" href="{% url 'done' appointment.id %}"><i class="far fa-times-circle"></i></a>
                          </td>
                        {% endif %}
                      </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          {% else %}
            <p>You have not made any appointment</p>
          {% endif %}
    </div>
    </div>
</div>
{% endblock contant %}

templates/mentors/mentor_history.html
{% extends 'base.html' %}
{% load static %}
{% block contant %}
<!-- Mentor home navbar -->
<div class="container">
    {% include 'partials/_alerts.html' %}
<div class="row">
    <div class="col-sm-3">
        {% include 'partials/_userHNav.html' %}
    </div>
    <div class="col-sm-9">
        {% if appointment %}
          <table class="table table-striped table-sm mt-2 search_bar_color">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Name</th>
                  <th scope="col">Phone</th>
                  <th scope="col">Apply Date</th>
                  <th scope="col">Appointment Date</th>
                  <th scope="col">Profile</th>
                  <th scope="col">Is Done</th>
                </tr>
              </thead>
              <tbody>
                {% for appointment in appointment %}
                  <tr>
                      <th scope="row">{{ forloop.counter }}</th>
                      <td>{{ appointment.name }}</td>
                      <td>{{ appointment.phone }}</td>
                      <td>{{ appointment.apply_date_pretty }}</td>
                      {% if appointment.appointment_date %}
                        <td>{{ appointment.appointment_date_pretty }}</td>
                      {% else %}
                        <td>
                          <form action="{% url 'appointmentDate' appointment.id %}" method="POST" class="form-inline">
                            {% csrf_token %}
                            <div class="form-group">
                              <input type="datetime-local" name="appointment_date" class="form-control form-control-sm">
                            </div>
                            <input type="submit" class="btn btn-success btn-sm" value="&#10003">
                          </form>
                      </td>
                      {% endif %}
                      <!-- View Profile -->
                      <td><a href="{% url 'view_profile' appointment.user_id %}" class="btn btn-secondary" >View</a></td>
                      <td class="align-middle">
                        {% if appointment.done_job %}
                          <td class="text-success"><i class="fas fa-check-circle"></i></td>
                        {% else %}
                          <td class="align-middle">
                            <a class="text-danger" href="{% url 'done' appointment.id %}"><i class="far fa-times-circle"></i></a>
                          </td>
                        {% endif %}
                      </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          {% else %}
            <p>You have not made any appointment</p>
          {% endif %}
    </div>
    </div>
</div>
{% endblock contant %}

templates/mentors/mentors_details.html
{% extends 'base.html' %}
{% load static %}
{% block contant %}
    <!-- Title name -->
    <section id="showcase-inner" class="py-5 text-white search_bar_color">
        <div class="container">
          <div class="row text-center">
            <div class="col-md-12">
              <h1 class="display-4">{{ mentors_details.title }}</h1>
              <p class="lead">
                {% if mentors_details.mentors_picture %}
                  <img class="rounded-circle mr-2" src="{{mentors_details.mentors_picture.url}}" width="30" height="30"/>
                {% else %}
                  <img class="rounded-circle mr-2" src="{% static 'img/default_dp.jpg' %}" width="30" height="30"/>
                {% endif %}{{ mentors_details.mentor_Name }}</p>
            </div>
          </div>
        </div>
      </section>
      {% include 'partials/_alerts.html' %}
    <!-- Breadcrumb -->
    <section id="bc" class="mt-3">
        <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'index' %}">
                <i class="fas fa-home"></i> Home</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'mentors_list' %}">Mentors List</a>
            </li>
            <li class="breadcrumb-item active"> {{ mentors_details.name }}</li>
            </ol>
        </nav>
        </div>
    </section>

    <!-- Details Area -->
    <!-- Banner -->
      <div class="container">
        <div class="row">
          <div id="carouselExampleControls" class="carousel slide col-md-9" data-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active">
                {% if mentors_details.cover_photo_1 %}
                  <img class="d-block w-100" width="600" height="390" src="{{ mentors_details.cover_photo_1.url }}" alt="First slide">
                {% else %}
                  <img class="d-block w-100" width="600" height="390" src="{% static 'img/default_cvp.jpg' %}"/>
                {% endif %}
              </div>
              {% if mentors_details.cover_photo_2 %}
              <div class="carousel-item">
                <img class="d-block w-100" width="600" height="390" src="{{ mentors_details.cover_photo_2.url }}" alt="Second slide">
              </div>
              {% endif %}
              {% if mentors_details.cover_photo_3 %}
              <div class="carousel-item">
                <img class="d-block w-100" width="600" height="390" src="{{ mentors_details.cover_photo_3.url }}" alt="Third slide">
              </div>
              {% endif %}
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
          <!-- Side Bar Mentor Picture -->
          <div class="col-md-3">
            <div class="card mb-3">
              {% if mentors_details.mentors_picture %}
                <img class="card-img-top" src="{{ mentors_details.mentors_picture.url }}" width="200" height="250">
              {% else %}
                <img class="card-img-top" src="{% static 'img/default_dp.jpg' %}" width="200" height="250">
              {% endif %}
              <div class="card-body">
                <h5 class="card-title">{{ mentors_details.mentor_Name }}</h5>
                <h6 class="text-secondary"> {{ mentors_details.get_catagory_display }} Mentor </h6>
                  <!-- This form for booking appointment -->
                  <form action="{% url 'appointment' %}" method="POST" >
                    {% csrf_token %}
                    <!-- All hidden field -->
                    <input type="hidden" name="user_id" value="{{ user.id }}">
                    <input type="hidden" name="mentor_id" value="{{ mentors_details.id }}">
                    <input type="hidden" name="listing_id" value="{{ listing.id }}">
                    <input type="hidden" name="visiting_free" value="{{ mentors_details.visiting_fees }}">
                    <input type="hidden" name="mentorUsername" value="{{ mentors_details.mentor_Name.username }}">
                    <input type="hidden" name="mentor_Name" class="form-control" value="{{mentors_details.mentor_Name}}">
                    <input type="hidden" name="category" class="form-control" value="{{ mentors_details.get_catagory_display }}">
                    <input type="hidden" name="name" class="form-control" value="{{user.first_name}} {{ user.last_name }}" required>
                    <input type="hidden" name="email" class="form-control" value="{{user.email}}">
                    <input type="hidden" name="phone" class="form-control" value="{{user.phone_number}}">
                    <input type="submit" value="Book An Appointment" class="btn btn-block btn-secondary">
                  </form>
                  <!-- End of booking appointment form -->
              </div>  
          </div>
        </div>
      </div>
      <!-- Fields -->
      <div class="row mb-5 fields">
        <div class="col-md-8">
          <ul class="list-group list-group-flush">
            <li class="list-group-item text-secondary">
              <i class="fas fa-graduation-cap"></i> Professional Degree :
              <span class="float-right">{{ mentors_details.professional_degree  }}</span>
            </li>
            <li class="list-group-item text-secondary">
              <i class="fas fa-crown"></i> Designation:
              <span class="float-right">{{ mentors_details.designation }}</span>
            </li>
            <li class="list-group-item text-secondary">
              <i class="fas fa-magic"></i> Specialist On :
              <span class="float-right">{{ mentors_details.specialist_in }}</span>
            </li>
            <li class="list-group-item text-secondary">
              <i class="fas fa-clock"></i> Visiting Hour :
              <span class="float-right">{{ mentors_details.visiting_houre }}
              </span>
            </li>
            <li class="list-group-item text-secondary">
                <i class="fas fa-money-bill-wave"></i> Visiting Fees :
              <span class="float-right">৳{{ mentors_details.visiting_fees }}
              </span>
            </li>
            <li class="list-group-item text-secondary">
                <i class="fas fa-map-marker-alt"></i> Chember Location :
              <span class="float-right">{{ mentors_details.chamber_address }}
              </span>
            </li>
          </ul>
        </div>
      </div>

      <!-- Description -->
      <div class="row mb-5">
        <div class="col-md-8"> {{ mentors_details.descriptions }} </div>
      </div>
{% endblock %}

templates/mentors/mentors_list.html
{% extends 'base.html' %}
{% load static %}
{% block contant %}
    <section id="showcase-inner" class="py-5 text-white search_bar_color">
        <div class="container">
        <div class="row text-center">
            <div class="col-md-12">
            <h1 class="display-4">Browse Our Mentors</h1>
            <p class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt, pariatur!</p>
            </div>
        </div>
        </div>
    </section>

    <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'index' %}">
              <i class="fas fa-home"></i> Home</a>
          </li>
          <li class="breadcrumb-item active"> Browse Mentors</li>
        </ol>
      </nav>
    </div>
  </section>

  <!-- Mentors List -->
  <section id="listings" class="py-5">
    <div class="container">
    <div class="row">
        {% if mentors %}
        {% for mentor in mentors %}
          <div class="col-md-6 col-lg-4 mb-4">
              <div class="card">
                {% if mentor.cover_photo_1 %}
                <img class="card-img-top" width="330px" height="220px" src="{{ mentor.cover_photo_1.url  }}" alt="">
                {% else %}
                <img class="card-img-top" width="330px" height="220px" src="{% static 'img/default_cvp.jpg' %}"/>
                {% endif %}
              <div class="card-body">
                  <div class="listing-heading text-center">
                  <h5 class="h4text">{{ mentor.title }}</h5>
                  <p>
                    {% if mentor.mentors_picture %}
                        <img class="rounded-circle mr-2" src="{{mentor.mentors_picture.url}}" width="25" height="25"/>
                    {% else %}
                      <img class="rounded-circle mr-2" src="{% static 'img/default_dp.jpg' %}" width="25" height="25"/>
                    {% endif %} {{ mentor.mentor_Name }}</p>
                  </div>
                  
                  <div class="row py-2 text-secondary">
                  <p>{{ mentor.summary }}</p>
                  </div>
                  <a href="{% url 'mentors_details' mentor.id %}" class="btn btn-secondary btn-block stretched-link">More Info</a>
              </div>
              </div>
          </div>
      {% endfor %}
            {% else%}
              <div class="col-md-12">
                <p>No Mentors Available</p>
              </div>
            {% endif %}
    </div>
    <div class="row">
      <div class="col-md-12">
        <ul class="pagination">
          {% if mentors.has_previous %}
          <li class="page-item">
            <a class="page-link h4text" href="?page={{ mentors.previous_page_number }}">&laquo;</a>
          </li>
          <li class="page-item">
            <a class="page-link h4text" href="?page={{ mentors.previous_page_number }}">{{ mentors.previous_page_number }}</a>
          </li>
          {% else %}
          <li class="page-item disabled">
            <a class="page-link h4text" href="">&laquo;</a>
          </li>
          {% endif %}
          <li class="page-item active">
            <a class="page-link nav_bg" href="?page={{ mentors.number }}">{{ mentors.number }}</a>
          </li>
          {% if mentors.has_next %}
          <li class="page-item">
            <a class="page-link h4text" href="?page={{ mentors.next_page_number }}">{{ mentors.next_page_number}}</a>
          </li>
          <li class="page-item">
            <a class="page-link h4text" href="?page={{ mentors.next_page_number }}">&raquo;</a>
          </li>
          {% else %}
          <li class="page-item disabled">
            <a class="page-link h4text" href="">&raquo;</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
    </div>
    </section>
{% endblock %}

templates/mentors/search.html
{% extends 'base.html' %}
{% load static %}
{% block contant %}
<section id="showcase-inner" class="showcase-search text-white py-5 search_bar_color">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <form action="{% url 'search' %}">
            <!-- Form Row 1 -->
            <div class="form-row">
              <div class="col-md-6 mb-3">
                <label class="sr-only">Keywords</label>
                <input type="text" name="keywords" class="form-control" placeholder="Search Mentor By Keywords">
              </div>

              <div class="col-md-6 mb-3">
                <label class="sr-only">Mentor Name</label>
                <input type="text" name="name" class="form-control" placeholder="Search By Mentor Name">
              </div>
            </div>
            <!-- Form Row 2 -->
            <div class="form-row">
              <div class="col-md-4 mb-3">
                <label class="sr-only">Category</label>
                <select name="category" class="form-control">
                  <option selected="true" disabled="disabled">Category (All)</option>
                  {% for key,value in category.items %}
                    <option value="{{ key }}">{{ value }}</option>
                  {% endfor %}
                </select>
              </div>
              <div class="col-md-4 mb-3">
                <label class="sr-only">District</label>
                <select name="district" class="form-control">
                  <option selected="true" disabled="disabled">District (All)</option>
                  {% for key,value in district_list.items %}
                    <option value="{{ key }}">{{ value }}</option>
                  {% endfor %}
                </select>
              </div>
              <div class="col-md-4 mb-3">
                <label class="sr-only">Divisions</label>
                <select name="division" class="form-control">
                  <option selected="true" disabled="disabled">Divisions (All)</option>
                  {% for key,value in divisions_list.items %}
                    <option value="{{ key }}">{{ value }}</option>
                  {% endfor %}
                </select>
              </div>
            </div>
            <button class="btn btn-secondary btn-block mt-4" type="submit">Let's find!</button>
          </form>
        </div>
      </div>
    </div>
  </section>
    <!-- Breadcrumb -->
    <section id="bc" class="mt-3">
        <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'index' %}">
                <i class="fas fa-home"></i> Home</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'mentors_list' %}">Browse Mentors</a>
            </li>
            <li class="breadcrumb-item active"> Search Results</li>
            </ol>
        </nav>
        </div>
    </section>

    <!-- Listings -->
  <section id="listings" class="py-5">
      <div class="container">
      <h3 class="text-center mb-3 h4text">Search Results<hr></h3>
      <div class="row">
          {% if mentors %}
          {% for mentor in mentors %}
            <div class="col-md-6 col-lg-4 mb-4">
                <div class="card">
                  {% if mentor.cover_photo_1 %}
                  <img class="card-img-top" width="330px" height="220px" src="{{ mentor.cover_photo_1.url  }}" alt="">
                  {% else %}
                  <img class="card-img-top" width="330px" height="220px" src="{% static 'img/default_cvp.jpg' %}"/>
                  {% endif %}
                <div class="card-body">
                    <div class="listing-heading text-center">
                    <h5 class="h4text">{{ mentor.title }}</h5>
                    <p>
                      {% if mentor.mentors_picture %}
                          <img class="rounded-circle mr-2" src="{{mentor.mentors_picture.url}}" width="25" height="25"/>
                      {% else %}
                        <img class="rounded-circle mr-2" src="{% static 'img/default_dp.jpg' %}" width="25" height="25"/>
                      {% endif %} {{ mentor.mentor_Name }}</p>
                    </div>
                    
                    <div class="row py-2 text-secondary">
                    <p>{{ mentor.summary }}</p>
                    </div>
                    <a href="{% url 'mentors_details' mentor.id %}" class="btn btn-secondary btn-block stretched-link">More Info</a>
                </div>
                </div>
            </div>
        {% endfor %}
        {% else%}
          <div class="col-md-12">
            <p>No Mentors Available</p>
          </div>
        {% endif %}        
      </div>
      </div>
  </section>
{% endblock %}